<?php

namespace AD\SoireeBundle\Repository;

/**
 * PratiquerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PratiquerRepository extends \Doctrine\ORM\EntityRepository
{
}
