<?php

namespace AD\CoreBundle\Repository;

/**
 * DanseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DanseRepository extends \Doctrine\ORM\EntityRepository
{
}
