

<?php

namespace AD\StageBundle\Repository;

/**
 * ReglementstageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReglementstageRepository extends \Doctrine\ORM\EntityRepository
{
}

