<?php

namespace AD\StageBundle\Repository;

/**
 * StagiaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StagiaireRepository extends \Doctrine\ORM\EntityRepository
{
}

