AD\PresaisonBundle\Entity\Coursinitiation:
    type: entity
    table: coursinitiation
    indexes:
        I_FK_coursInitiation_soiree:
            columns:
                - idSoiree
        I_FK_coursInitiation_danse:
            columns:
                - idDanse
        I_FK_coursInitiation_salle:
            columns:
                - idSalle
    id:
        idinitiation:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: idInitiation
            generator:
                strategy: IDENTITY
    manyToOne:
        idsalle:
            targetEntity: Salle
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idSalle:
                    referencedColumnName: idSalle
            orphanRemoval: false
        idsoiree:
            targetEntity: Soiree
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idSoiree:
                    referencedColumnName: idSoiree
            orphanRemoval: false
        iddanse:
            targetEntity: Danse
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idDanse:
                    referencedColumnName: idDanse
            orphanRemoval: false
    lifecycleCallbacks: {  }
