AD\PresaisonBundle\Entity\Danse:
    type: entity
    table: danse
    id:
        iddanse:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: idDanse
            generator:
                strategy: IDENTITY
    fields:
        nomdanse:
            type: string
            nullable: true
            length: 32
            fixed: true
            column: nomDanse
        descrdanse:
            type: string
            nullable: true
            length: 255
            fixed: true
            column: descrDanse
    manyToMany:
        idtypeforfait:
            targetEntity: Typeforfait
            cascade: {  }
            mappedBy: null
            inversedBy: iddanse
            joinTable:
                name: danseciblee
                joinColumns:
                    -
                        name: idDanse
                        referencedColumnName: idDanse
                inverseJoinColumns:
                    -
                        name: idTypeForfait
                        referencedColumnName: idTypeForfait
            orderBy: null
        idniveau:
            targetEntity: Niveau
            cascade: {  }
            mappedBy: iddanse
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
