AD\PresaisonBundle\Entity\Lieu:
    type: entity
    table: lieu
    id:
        idlieu:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            column: idLieu
            generator:
                strategy: IDENTITY
    fields:
        nomlieu:
            type: string
            nullable: true
            length: 32
            fixed: true
            column: nomLieu
        adresselieu:
            type: string
            nullable: true
            length: 32
            fixed: true
            column: adresseLieu
    lifecycleCallbacks: {  }
