AD\PresaisonBundle\Entity\Reduction:
    type: entity
    table: reduction
    id:
        idreduction:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: idReduction
            generator:
                strategy: IDENTITY
    fields:
        typereduction:
            type: string
            nullable: true
            length: 32
            fixed: true
            column: typeReduction
        montantreduction:
            type: integer
            nullable: true
            unsigned: false
            column: montantReduction
    lifecycleCallbacks: {  }
