AD\PresaisonBundle\Entity\Reglementstage:
    type: entity
    table: reglementstage
    indexes:
        I_FK_reglementStage_stage:
            columns:
                - idStage
        I_FK_reglementStage_stagiaire:
            columns:
                - idStagiaire
    id:
        idreglementstage:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: idReglementStage
            generator:
                strategy: IDENTITY
    fields:
        datereglement:
            type: date
            nullable: true
            column: dateReglement
        montantreglement:
            type: integer
            nullable: true
            unsigned: false
            column: montantReglement
        etatreglement:
            type: string
            nullable: true
            length: 32
            fixed: true
            column: etatReglement
    manyToOne:
        idstagiaire:
            targetEntity: Stagiaire
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idStagiaire:
                    referencedColumnName: idStagiaire
            orphanRemoval: false
        idstage:
            targetEntity: Stage
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idStage:
                    referencedColumnName: idStage
            orphanRemoval: false
    lifecycleCallbacks: {  }
