AD\PresaisonBundle\Entity\Saison:
    type: entity
    table: saison
    id:
        idsaison:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: idSaison
            generator:
                strategy: IDENTITY
    fields:
        annee:
            type: integer
            nullable: true
            unsigned: false
        tarifadhesion:
            type: integer
            nullable: true
            unsigned: false
            column: tarifAdhesion
    manyToMany:
        idadherent:
            targetEntity: Adherent
            cascade: {  }
            mappedBy: idsaison
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
