AD\PresaisonBundle\Entity\Salle:
    type: entity
    table: salle
    indexes:
        I_FK_salle_lieu:
            columns:
                - idLieu
    id:
        idsalle:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: idSalle
            generator:
                strategy: IDENTITY
    fields:
        nomsalle:
            type: string
            nullable: true
            length: 32
            fixed: true
            column: nomSalle
        capacite:
            type: integer
            nullable: true
            unsigned: false
    manyToOne:
        idlieu:
            targetEntity: Lieu
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idLieu:
                    referencedColumnName: idLieu
            orphanRemoval: false
    lifecycleCallbacks: {  }
