AD\PresaisonBundle\Entity\Soiree:
    type: entity
    table: soiree
    indexes:
        I_FK_soiree_lieu:
            columns:
                - idLieu
    id:
        idsoiree:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: idSoiree
            generator:
                strategy: IDENTITY
    fields:
        intitule:
            type: string
            nullable: true
            length: 32
            fixed: true
        datesoiree:
            type: date
            nullable: true
            column: dateSoiree
        heuredebutsoiree:
            type: time
            nullable: true
            column: heureDebutSoiree
        heurefinsoiree:
            type: time
            nullable: true
            column: heureFinSoiree
        dressecode:
            type: string
            nullable: true
            length: 32
            fixed: true
            column: dresseCode
        tarifsoiree:
            type: integer
            nullable: true
            unsigned: false
            column: tarifSoiree
    manyToOne:
        idlieu:
            targetEntity: Lieu
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idLieu:
                    referencedColumnName: idLieu
            orphanRemoval: false
    lifecycleCallbacks: {  }
