AD\PresaisonBundle\Entity\Stagiaire:
    type: entity
    table: stagiaire
    id:
        idstagiaire:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: idStagiaire
            generator:
                strategy: IDENTITY
    fields:
        nomstagiaire:
            type: string
            nullable: true
            length: 32
            fixed: true
            column: nomStagiaire
        prenomstagiaire:
            type: string
            nullable: true
            length: 32
            fixed: true
            column: prenomStagiaire
        telstagiaire:
            type: integer
            nullable: true
            unsigned: false
            column: telStagiaire
    manyToMany:
        idstage:
            targetEntity: Stage
            cascade: {  }
            mappedBy: idstagiaire
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
