AD\PresaisonBundle\Entity\Typereglement:
    type: entity
    table: typereglement
    id:
        idtypereglement:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: idTypeReglement
            generator:
                strategy: IDENTITY
    fields:
        typereglement:
            type: string
            nullable: true
            length: 32
            fixed: true
            column: typeReglement
    lifecycleCallbacks: {  }
