<?php

namespace AD\CoreBundle\Repository;

/**
 * CoursinitiationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursinitiationRepository extends \Doctrine\ORM\EntityRepository
{
}
