<?php

namespace AD\CoreBundle\Repository;

/**
 * QualifierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QualifierRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByQualifier($idniveau, $idprof, $iddanse)
		{
		  $qb = $this->createQueryBuilder('q');
		  $qb->where('q.idniveau = :idniveau')
			   ->setParameter('idniveau', $idniveau)
			 ->andWhere('q.idprof = :idprof')
			   ->setParameter('idprof', $idprof)
			   ->andWhere('q.iddanse = :iddanse')
			   ->setParameter('iddanse', $iddanse)  ;
			  return $qb
				->getQuery()
				->getOneOrNullResult() ;
}
}

