<?php

namespace AD\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReglementstageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReglementstageRepository extends EntityRepository
{
}
