<?php

namespace AD\CoreBundle\Repository;

/**
 * TypeforfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeforfaitRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByTypeForfaitCurrent($idtypeforfait)
		{
		  $qb = $this->createQueryBuilder('t');
		  $qb->where('t.idtypeforfait = :idtypeforfait')
			   ->setParameter('idtypeforfait', $idtypeforfait) ;
				return $qb
				->getQuery()
				->getResult()
			  ;
}
}
