<?php

namespace AD\PresaisonBundle\Repository;

/**
 * CourshebdomadaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourshebdomadaireRepository extends \Doctrine\ORM\EntityRepository
{
}
