<?php

namespace AD\PresaisonBundle\Repository;

/**
 * QualifierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QualifierRepository extends \Doctrine\ORM\EntityRepository
{
}
